export const unitCardStyles = {
  base: "bg-white rounded-lg shadow-sm border border-gray-200 p-6 hover:shadow-md transition-shadow",
  locked: "opacity-60",
  unlocked: "cursor-pointer",
  title: "font-semibold text-lg text-gray-800",
  description: "text-gray-600 text-sm mb-4",
  difficulty: {
    base: "px-2 py-1 rounded-full text-xs font-medium",
    beginner: "bg-green-100 text-green-800",
    intermediate: "bg-yellow-100 text-yellow-800",
    advanced: "bg-red-100 text-red-800",
    default: "bg-gray-100 text-gray-800",
  },
  timeInfo: "flex items-center text-gray-500",
  timeIcon: "mr-1",
  progressContainer: "space-y-2",
  progressLabel: "text-sm text-gray-600",
  progressValue: "text-sm font-medium text-gray-800",
  progressBar: {
    container: "w-full bg-gray-200 rounded-full h-2",
    fill: "bg-blue-600 h-2 rounded-full transition-all duration-300",
  },
  topicsSection: "pt-3 border-t border-gray-100",
  topicsLabel: "text-xs text-gray-500 mb-2",
  topicsContainer: "flex flex-wrap gap-1",
  topicTag: "text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded",
  moreTopics: "text-xs text-gray-500",
  actionButton:
    "w-full mt-4 bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition-colors",
};
