export const curriculumGridStyles = {
  container: "space-y-12",
  progressGrid: "grid grid-cols-1 md:grid-cols-4 gap-4 mb-8",
  progressCard: "bg-white rounded-lg shadow-sm border border-gray-200 p-4",
  progressItem: "flex items-center space-x-2",
  progressIcon: {
    base: "w-8 h-8 rounded-full flex items-center justify-center",
    blue: "bg-blue-100",
    yellow: "bg-yellow-100",
    green: "text-green-500",
    purple: "text-purple-500",
  },
  progressText: {
    label: "text-sm text-gray-500",
    value: "font-semibold text-gray-800",
  },
  learningPath: "space-y-8",
  pathHeader: "flex items-center justify-between",
  pathTitle: "text-xl font-semibold text-gray-800",
  pathDescription: "text-sm text-gray-600",
  accordion: "space-y-4",
  accordionItem: "bg-white rounded-lg shadow-sm border border-gray-200",
  accordionTrigger: "p-6 hover:no-underline",
  unitHeader: "flex items-start justify-between w-full",
  unitContent: "flex-1 text-left",
  unitInfo: "flex items-center space-x-3 mb-2",
  unitIcon: {
    base: "w-8 h-8 rounded-full flex items-center justify-center",
    completed: "bg-green-500",
    inProgress: "bg-blue-500",
  },
  unitTitle: "text-lg font-semibold text-gray-800",
  difficultyBadge: {
    base: "px-2 py-1 rounded-full text-xs font-medium",
    beginner: "bg-green-100 text-green-800",
    intermediate: "bg-yellow-100 text-yellow-800",
    advanced: "bg-red-100 text-red-800",
    default: "bg-gray-100 text-gray-800",
  },
  unitDescription: "text-gray-600 mb-3",
  progressBar: {
    container: "flex items-center space-x-4",
    bar: "flex items-center space-x-2",
    track: "w-32 bg-gray-200 rounded-full h-2",
    fill: {
      base: "h-2 rounded-full transition-all duration-300",
      completed: "bg-green-500",
      inProgress: "bg-blue-500",
    },
    percentage: "text-sm text-gray-600",
  },
  accordionContent: "px-6 pb-6",
  topicsContainer: "space-y-3",
  topicItem: {
    base: "flex items-center justify-between p-4 rounded-lg border transition-colors",
    completed: "bg-green-50 border-green-200",
    locked: "bg-gray-50 border-gray-200 opacity-60",
    available: "bg-gray-50 border-gray-200 hover:bg-gray-100 cursor-pointer",
  },
  topicContent: "flex items-center space-x-3",
  topicIcon: {
    base: "w-6 h-6 rounded-full flex items-center justify-center text-xs font-medium",
    completed: "bg-green-500 text-white",
    locked: "bg-gray-300 text-gray-500",
    available: "bg-blue-500 text-white",
  },
  topicInfo: "flex-1",
  topicTitle: "font-medium text-gray-800",
  topicDescription: "text-sm text-gray-600",
  topicMeta: "flex items-center space-x-4 mt-1",
  topicDuration: "flex items-center space-x-1",
  durationIcon: "w-3 h-3 text-gray-400",
  durationText: "text-xs text-gray-500",
  typeBadge: {
    base: "px-2 py-0.5 rounded text-xs font-medium",
    theory: "bg-blue-100 text-blue-800",
    exercise: "bg-green-100 text-green-800",
    assessment: "bg-purple-100 text-purple-800",
    default: "bg-gray-100 text-gray-800",
  },
  topicActions: "flex items-center space-x-2",
  statusBadge: {
    completed:
      "text-xs text-green-600 font-medium bg-green-100 px-2 py-1 rounded",
    locked: "text-xs text-gray-500 font-medium",
  },
  startButton:
    "flex items-center space-x-1 text-blue-600 hover:text-blue-700 text-sm font-medium",
  continueSection:
    "bg-gradient-to-r from-blue-50 to-purple-50 rounded-lg p-6 border",
  continueContent: "flex items-center justify-between",
  continueInfo: "",
  continueTitle: "text-lg font-semibold text-gray-800 mb-2",
  continueDescription: "text-gray-600 mb-1",
  continueProgress: "flex items-center space-x-2 text-sm text-gray-600",
  continueButton:
    "bg-blue-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-blue-700 transition-colors",
};
